# Some of Bioconda's supported versions are described
# in ../docs/source/user/versions.rst
# so please keep that documentation up to date as they change

# Additional bioconda-specific pinnings to use in addition to those specified
# in
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

# clear hard-coded default value for CONDA_BUILD_SYSROOT
CONDA_BUILD_SYSROOT:
  - ''

pin_run_as_build:
  htslib:
    max_pin: x.x
  bamtools:
    max_pin: x.x.x
  r-base:
    max_pin: x.x
    min_pin: x.x

htslib:
  - 1.10
bamtools:
  - 2.5.1

# NOTE: Workaround https://github.com/conda/conda-build/issues/3974 we slightly alter the values
#       from conda-forge-pinnings here (inserting '.*' or ' ' which should be ignored later on).
r_base:
  - 4.0.*
python:
  - 3.9.*  *_cpython
  - 3.8.*  *_cpython
  - 3.7.*  *_cpython
  - 3.6.*  *_cpython
  - 2.7.*  *_cpython

c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
c_compiler_version:            # [unix]
  - 9                          # [osx]
  - 7                          # [linux64 or aarch64]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
cxx_compiler_version:          # [unix]
  - 9                          # [osx]
  - 7                          # [linux64 or aarch64]
fortran_compiler:              # [unix or win64]
  - gfortran                   # [(linux64 or osx)]
fortran_compiler_version:      # [unix or win64]
  - 7                          # [linux64 or osx or aarch64]

